version: '3.3'

services:
  web:
    image: evgev/pk:latest
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-i", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 3  
    env_file: .env

  postgres42:
    image: postgres:14.6-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data:cached
      - ./dumps/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "pkbase_production"]
      interval: 5s
    env_file: .env

volumes:
  postgres_volume: